include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_single_quotes

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
