include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs
    - prefer_final_locals
    - avoid_returning_null_for_future
    - prefer_single_quotes

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
