name: flutter_smart_debouncer_widgets
version: 0.1.0

description: Flutter widgets built on top of flutter_smart_debouncer.
repository: https://github.com/example/flutter_smart_debouncer
issue_tracker: https://github.com/example/flutter_smart_debouncer/issues
homepage: https://github.com/example/flutter_smart_debouncer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_debouncer:
    path: ../flutter_smart_debouncer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
