name: Dart CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/flutter_smart_debouncer
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test

  widgets:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/flutter_smart_debouncer_widgets
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test
